import { createContext, useContext, useEffect, useState } from 'react'

const LanguageContext = createContext(null)

export const translations = {
  fr: {
    // Sidebar
    nav:           'Navigation',
    dashboard:     'Dashboard',
    employees:     'Employés',
    attendance:    'Suivi Quotidien',
    schedules:     'Horaires',
    reports:       'Rapports',
    leaves:        'Congés',
    lightMode:     'Mode clair',
    darkMode:      'Mode sombre',
    logout:        'Déconnexion',
    appSubtitle:   'Gestion des Présences',

    // Dashboard
    dashboardTitle:  'Tableau de bord',
    online:          'En ligne',
    offline:         'Hors ligne',
    refresh:         'Actualiser',
    totalEmployees:  'Total Employés',
    present:         'Présents',
    late:            'En retard',
    absent:          'Absents',
    registered:      'enregistrés',
    today:           "aujourd'hui",
    liveFeed:        'Pointages en direct',
    noAttendance:    "Aucun pointage aujourd'hui",
    employee:        'Employé',
    time:            'Heure',
    date:            'Date',
    newBadge:        'NOUVEAU',
    sync:            'Sync',
    page:            'Page',
    of:              'sur',
    punches:         'pointage(s)',

    // Employees
    employeesTitle:  'Employés',
    addEmployee:     'Ajouter un employé',
    searchEmployee:  'Rechercher un employé...',
    name:            'Nom',
    department:      'Département',
    position:        'Poste',
    zkId:            'ID ZKTeco',
    status:          'Statut',
    actions:         'Actions',
    active:          'Actif',
    inactive:        'Inactif',
    edit:            'Modifier',
    delete:          'Supprimer',
    save:            'Enregistrer',
    cancel:          'Annuler',
    firstName:       'Prénom',
    lastName:        'Nom de famille',
    noEmployees:     'Aucun employé trouvé',
    confirmDelete:   'Supprimer cet employé ?',

    // Attendance
    attendanceTitle: 'Suivi Quotidien',
    filterEmployee:  'Nom employé...',
    filterFrom:      'Du',
    filterTo:        'Au',
    applyFilter:     'Filtrer',
    resetFilter:     'Réinitialiser',
    noAttendanceRec: 'Aucun enregistrement',
    statusPresent:   'Présent',
    statusLate:      'En retard',
    statusAbsent:    'Absent',
    onLeave:         'En congé',
    scans:           'Pointages',
    noScans:         'Aucun scan',
    previous:        'Précédent',
    next:            'Suivant',

    // Reports
    reportsTitle:    'Rapports Mensuels',
    reportsSub:      'Récapitulatif des présences par employé',
    exportCSV:       'Exporter CSV',
    totalHours:      'Total heures',
    month:           'Mois',

    // Schedules
    schedulesTitle:  'Horaires de Travail',
    schedulesSub:    'Configurez les plages de travail et la tolérance',
    addSchedule:     'Ajouter',
    startTime:       'Heure d\'entrée',
    endTime:         'Heure de sortie',
    gracePeriod:     'Tolérance (minutes)',
    noSchedules:     'Aucun horaire configuré',
    scheduleName:    'Nom de l\'horaire',
    scheduleEntry:   'Entrée',
    scheduleExit:    'Sortie',
    scheduleTol:     'Tolérance',
    scheduleActive:  'Horaire actif',
    editSchedule:    'Modifier l\'horaire',
    confirmSchedule: 'Supprimer cet horaire ?',

    // Attendance page
    checkIn:         'Entrée',
    checkOut:        'Sortie',
    duration:        'Durée',
    details:         'Détails',
    scanTimeline:    'Chronologie des pointages',
    noRecord:        'Aucun enregistrement trouvé',
    records:         'enregistrements',
    reset:           'Réinitialiser',

    // Reports page
    reportsOvertimeCol: 'Heures trav. + mission',
    hoursWorked:     'Heures trav.',
    exportPDF:       'Export PDF',
    noData:          'Aucune donnée pour cette période',

    // Leaves page
    leavesTitle:     'Gestion des Congés',
    leavesSub:       'Congés, absences justifiées et missions',
    newLeave:        'Nouveau congé',
    leaveFrom:       'Date début',
    leaveTo:         'Date fin',
    leaveType:       'Type',
    leaveNote:       'Note',
    leaveAction:     'Action',
    leaveEmployee:   'Employé',
    leaveDuration:   'Durée',
    leaveAnnual:     'Congé annuel',
    leaveSick:       'Arrêt maladie',
    leaveMission:    'Mission',
    leaveOther:      'Autre',
    noLeaves:        'Aucun congé enregistré pour cette période',
    confirmLeave:    'Supprimer ce congé ?',
    register:        'Enregistrer',
    saving:          'Enregistrement...',
    selectEmployee:  'Sélectionner...',
    optional:        'optionnel',
    days:            'jour(s)',

    // Photo
    clickToChangePhoto: 'Cliquer pour changer la photo',
    photoHint:          'JPG, PNG — max 3 Mo',

    // Justifications
    justifications:      'Justificatifs',
    justifTitle:         'Justificatifs de retard / absence',
    justifSub:           'Dépôt et validation des documents justificatifs',
    newJustif:           'Nouveau justificatif',
    justifDate:          'Date concernée',
    justifReason:        'Motif',
    justifFile:          'Fichier PDF',
    justifFileHint:      'PDF uniquement — max 5 Mo',
    justifRhNote:        'Commentaire RH',
    justifStatus:        'Statut',
    justifPending:       'En attente',
    justifApproved:      'Approuvé',
    justifRejected:      'Refusé',
    justifApprove:       'Approuver',
    justifReject:        'Refuser',
    justifViewFile:      'Voir PDF',
    justifNoFile:        'Sans fichier',
    justifAll:           'Tous',
    noJustifs:           'Aucun justificatif pour cette période',
    justifConfirm:       'Supprimer ce justificatif ?',
    reviewTitle:         'Décision RH',
    submit:              'Soumettre',

    // Employees list stats
    thisMonthShort:  'Ce mois',
    noOvertime:      'Aucune heure sup.',

    // Employee bio fields
    birthDate:          'Date de naissance',
    age:                'Âge',
    years:              'ans',
    cin:                'CIN',
    phone:              'Téléphone',
    email:              'Email',
    address:            'Adresse',
    hireDate:           'Date d\'embauche',
    contractType:       'Type de contrat',
    memberSince:        'Membre depuis',
    contractCdi:        'CDI',
    contractCdd:        'CDD',
    contractStage:      'Stage',
    contractFreelance:  'Freelance',
    personalInfo:       'Informations personnelles',
    workInfo:           'Informations professionnelles',
    notSpecified:       'Non renseigné',
    yearsOfService:     'ancienneté',

    // Profile
    backToEmployees:   'Retour aux employés',
    punctuality:       'Ponctualité',
    avgArrival:        'Arrivée moy.',
    thisMonth:         'ce mois',
    history30:         'Historique 30j',
    calendar:          'Calendrier',
    noHistory:         'Aucun pointage enregistré',
    overtime:          'Heures travaillées',
    punctualityRate:   'Taux de ponctualité ce mois',
    statusActive:      'Actif',
    statusInactive:    'Inactif',
    loading:           'Chargement...',
    colDate:           'Date',
    colEntry:          'Entrée',
    colExit:           'Sortie',
    colDuration:       'Durée',
    colStatus:         'Statut',
    dayLabels:         ['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'],
    monthNames:        ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  },

  ar: {
    // Sidebar
    nav:           'التنقل',
    dashboard:     'لوحة التحكم',
    employees:     'الموظفون',
    attendance:    'المتابعة اليومية',
    schedules:     'الجداول',
    reports:       'التقارير',
    leaves:        'الإجازات',
    lightMode:     'الوضع الفاتح',
    darkMode:      'الوضع الداكن',
    logout:        'تسجيل الخروج',
    appSubtitle:   'إدارة الحضور والغياب',

    // Dashboard
    dashboardTitle:  'لوحة التحكم',
    online:          'متصل',
    offline:         'غير متصل',
    refresh:         'تحديث',
    totalEmployees:  'إجمالي الموظفين',
    present:         'الحاضرون',
    late:            'المتأخرون',
    absent:          'الغائبون',
    registered:      'مسجل',
    today:           'اليوم',
    liveFeed:        'السجلات المباشرة',
    noAttendance:    'لا توجد سجلات اليوم',
    employee:        'الموظف',
    time:            'الوقت',
    date:            'التاريخ',
    newBadge:        'جديد',
    sync:            'مزامنة',
    page:            'صفحة',
    of:              'من',
    punches:         'سجل',

    // Employees
    employeesTitle:  'الموظفون',
    addEmployee:     'إضافة موظف',
    searchEmployee:  'بحث عن موظف...',
    name:            'الاسم',
    department:      'القسم',
    position:        'المنصب',
    zkId:            'معرف ZKTeco',
    status:          'الحالة',
    actions:         'الإجراءات',
    active:          'نشط',
    inactive:        'غير نشط',
    edit:            'تعديل',
    delete:          'حذف',
    save:            'حفظ',
    cancel:          'إلغاء',
    firstName:       'الاسم الأول',
    lastName:        'اسم العائلة',
    noEmployees:     'لا يوجد موظفون',
    confirmDelete:   'حذف هذا الموظف؟',

    // Attendance
    attendanceTitle: 'المتابعة اليومية',
    filterEmployee:  'اسم الموظف...',
    filterFrom:      'من',
    filterTo:        'إلى',
    applyFilter:     'تصفية',
    resetFilter:     'إعادة تعيين',
    noAttendanceRec: 'لا توجد سجلات',
    statusPresent:   'حاضر',
    statusLate:      'متأخر',
    statusAbsent:    'غائب',
    onLeave:         'في إجازة',
    scans:           'البصمات',
    noScans:         'لا توجد بصمات',
    previous:        'السابق',
    next:            'التالي',

    // Reports
    reportsTitle:    'التقارير الشهرية',
    reportsSub:      'ملخص الحضور لكل موظف',
    exportCSV:       'تصدير CSV',
    totalHours:      'إجمالي الساعات',
    month:           'الشهر',

    // Schedules
    schedulesTitle:  'جداول العمل',
    schedulesSub:    'تكوين أوقات العمل وفترات السماح',
    addSchedule:     'إضافة',
    startTime:       'وقت الدخول',
    endTime:         'وقت الخروج',
    gracePeriod:     'فترة السماح (دقيقة)',
    noSchedules:     'لا توجد جداول مضافة',
    scheduleName:    'اسم الجدول',
    scheduleEntry:   'الدخول',
    scheduleExit:    'الخروج',
    scheduleTol:     'السماح',
    scheduleActive:  'جدول نشط',
    editSchedule:    'تعديل الجدول',
    confirmSchedule: 'حذف هذا الجدول؟',

    // Attendance page
    checkIn:         'الدخول',
    checkOut:        'الخروج',
    duration:        'المدة',
    details:         'تفاصيل',
    scanTimeline:    'جدول البصمات',
    noRecord:        'لا توجد سجلات',
    records:         'سجل',
    reset:           'إعادة تعيين',

    // Reports page
    reportsOvertimeCol: 'ساعات العمل + مهمة',
    hoursWorked:     'ساعات العمل',
    exportPDF:       'تصدير PDF',
    noData:          'لا توجد بيانات لهذه الفترة',

    // Leaves page
    leavesTitle:     'إدارة الإجازات',
    leavesSub:       'الإجازات والغيابات المبررة والمهام',
    newLeave:        'إجازة جديدة',
    leaveFrom:       'تاريخ البداية',
    leaveTo:         'تاريخ النهاية',
    leaveType:       'النوع',
    leaveNote:       'ملاحظة',
    leaveAction:     'إجراء',
    leaveEmployee:   'الموظف',
    leaveDuration:   'المدة',
    leaveAnnual:     'إجازة سنوية',
    leaveSick:       'إجازة مرضية',
    leaveMission:    'مهمة',
    leaveOther:      'أخرى',
    noLeaves:        'لا توجد إجازات مسجلة لهذه الفترة',
    confirmLeave:    'حذف هذه الإجازة؟',
    register:        'تسجيل',
    saving:          'جارٍ التسجيل...',
    selectEmployee:  'اختر موظفاً...',
    optional:        'اختياري',
    days:            'يوم',

    // Photo
    clickToChangePhoto: 'انقر لتغيير الصورة',
    photoHint:          'JPG، PNG — بحد أقصى 3 ميغابايت',

    // Justifications
    justifications:      'المبررات',
    justifTitle:         'مبررات التأخر / الغياب',
    justifSub:           'رفع والتحقق من الوثائق المبررة',
    newJustif:           'مبرر جديد',
    justifDate:          'التاريخ المعني',
    justifReason:        'السبب',
    justifFile:          'ملف PDF',
    justifFileHint:      'PDF فقط — بحد أقصى 5 ميغابايت',
    justifRhNote:        'ملاحظة الموارد البشرية',
    justifStatus:        'الحالة',
    justifPending:       'في الانتظار',
    justifApproved:      'مقبول',
    justifRejected:      'مرفوض',
    justifApprove:       'قبول',
    justifReject:        'رفض',
    justifViewFile:      'عرض PDF',
    justifNoFile:        'بدون ملف',
    justifAll:           'الكل',
    noJustifs:           'لا توجد مبررات لهذه الفترة',
    justifConfirm:       'حذف هذا المبرر؟',
    reviewTitle:         'قرار الموارد البشرية',
    submit:              'إرسال',

    // Employees list stats
    thisMonthShort:  'هذا الشهر',
    noOvertime:      'لا ساعات إضافية',

    // Employee bio fields
    birthDate:          'تاريخ الميلاد',
    age:                'العمر',
    years:              'سنة',
    cin:                'رقم البطاقة',
    phone:              'الهاتف',
    email:              'البريد الإلكتروني',
    address:            'العنوان',
    hireDate:           'تاريخ التوظيف',
    contractType:       'نوع العقد',
    memberSince:        'عضو منذ',
    contractCdi:        'CDI',
    contractCdd:        'CDD',
    contractStage:      'تدريب',
    contractFreelance:  'مستقل',
    personalInfo:       'المعلومات الشخصية',
    workInfo:           'المعلومات المهنية',
    notSpecified:       'غير محدد',
    yearsOfService:     'أقدمية',

    // Profile
    backToEmployees:   'العودة إلى الموظفين',
    punctuality:       'الانضباط',
    avgArrival:        'متوسط الوصول',
    thisMonth:         'هذا الشهر',
    history30:         'السجل (30 يوم)',
    calendar:          'التقويم',
    noHistory:         'لا توجد سجلات بصمات',
    overtime:          'ساعات العمل',
    punctualityRate:   'نسبة الانضباط هذا الشهر',
    statusActive:      'نشط',
    statusInactive:    'غير نشط',
    loading:           'جارٍ التحميل...',
    colDate:           'التاريخ',
    colEntry:          'الدخول',
    colExit:           'الخروج',
    colDuration:       'المدة',
    colStatus:         'الحالة',
    dayLabels:         ['إث','ثل','أر','خم','جم','سب','أح'],
    monthNames:        ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('zk_lang') || 'fr')

  useEffect(() => {
    localStorage.setItem('zk_lang', lang)
    document.documentElement.setAttribute('lang', lang)
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr')
  }, [lang])

  const toggle = () => setLang(l => l === 'fr' ? 'ar' : 'fr')
  const tr = translations[lang]

  return (
    <LanguageContext.Provider value={{ lang, toggle, tr }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
